spring.application.name=farmacia-online
spring.datasource.url=jdbc:postgresql://localhost:5433/farmacia
spring.datasource.username=farmacia
spring.datasource.password=farmacia

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true